"""Suspicious

Revision ID: b38039afdb45
Revises: 2ef8e61bab44
Create Date: 2026-05-11 23:26:15.671057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38039afdb45'
down_revision: Union[str, None] = '2ef8e61bab44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('suspicious_dismissed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'suspicious_dismissed')
    # ### end Alembic commands ###
