"""Remove unused audit_log fields

Revision ID: 2ef8e61bab44
Revises: 
Create Date: 2026-05-11 22:56:53.222130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef8e61bab44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
